import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="px-[10px] md:px-[20px] lg:px-[60px] xl:px-[100px] 2xl:px-[240px] bg-secondary ">
          <Navbar />
        </div>
        {children}

        <div className="px-[10px] md:px-[20px] lg:px-[60px] xl:px-[100px] 2xl:px-[240px] bg-secondary ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
